### ISSUE TITLE
base_partner_merge duplicated with Odoo crm module

### ISSUE THREAD

**Issue by guewen** [OCA/partner-contact#196]
I noticed that the `base_partner_merge` module is duplicated with the official `crm` module which includes this wizard. They share the same model name, views, etc. so it produces weird effects when both are installed. The code seems roughly the same (it was a backport originally) but I didn't checked if we have patches on this module to push upstream (at least #182 and #183 I guess).

Should we remove this module?

**Comment by pedrobaeza** [comment]
Yeah, it seems to me also weird when I saw a few weeks ago some patches for this. I have in mind to make a _base_merger_ general module, but not on the near roadmap.

**Comment by rafaelbn** [comment]
Yes, it's duplicated.

**Comment by hbrunn** [comment]
@guewen @pedrobaeza @rafaelbn 
I see merit in this module because is gives you the ability to merge partners without getting all the cruft of crm.

I think the way to go is making it clear in the readme that this module doesn't do anything else than the crm module, and shouldn't be installed if the latter is installed. I just merged a PR that at least adds a proper readme amongst others.

Then we can copy base_partner_merge\* from crm - which we should, because it looks like there are some subtle improvements.

Or we could try to be smart and do

```
from openerp.addons.crm import base_partner_merge
```

in `__init__.py`, this always should give us the current code. Might be a problem if some environments only have the code that is actually installed, but in a standard environment, this should work. Then we could have some abstract model that pulls the relevant data files from the `crm` module in `_register_hook`. This way, it would look like it's its own module, but all code comes from `crm`. What do you think?

**Comment by pedrobaeza** [comment]
I see the import as the smartest option, and I don't think there should be a problem, because almost everyone has available all the core addons in their deployments.

**Comment by rafaelbn** [comment]
Well this proposal has sense :+1: .

For me (what I wish) is that base_partner_merge would improve functionality of CRM... see https://github.com/odoo/odoo/issues/10534
I Odoo is impossible to deduplicate comparing partners with `is a company` = true by VAT (for example)

In my experience this year with many migrations from other CRM, ERP, Account of any database to Odoo, is that if Odoo and OCA expect a big growing is because many companies will migrate from other software and this tools will be critical to have a qualified data base of customers.

**Comment by yvaucher** [comment]
See https://github.com/OCA/partner-contact/pull/274 in which I implemented what @hbrunn proposed.

**Comment by pedrobaeza** [comment]
Closing as the PR is merged.
