### ISSUE TITLE
Nutrition information

### ISSUE THREAD

**Issue by max3903** [OCA/partner-contact#335]
# partner_contact_height

Height: float
Height UOM: many2one with uom in the Distance category

# partner_contact_weight

Weight: float
Weight UOM: many2one with uom in the Weight category

# partner_contact_nutrition

Add a "Nutrition" tab on the partner form view. Only visible if the partner is an individual.

Calorie: float
Calorie UOM: many2one with uom
Fat: float
Fat UOM: many2one with uom
Protein: float
Protein UOM: many2one with uom
Carbohydrate: float
Carbohydrate UOM: many2one with uom

# partner_contact_nutrition_exclusion

Exclusions: many2many with product.product

# partner_contact_nutrition_allergen

Allergens: many2many with product.product

# partner_contact_nutrition_goal

Nutrition goal: selection between 'Lose weight', 'Maintain weight', and 'Gain weight'

# partner_contact_nutrition_activity_level

Activity level: selection between Sedentary, Moderately Active, Very Active, Extremely Active

# partner_contact_nutrition_diet

Diet: many2one with nutrition_diet. 
Nutrition_diet is only an object with a name field.  It can be extended later to have a list of inclusions or exclusions.
The module would provide the following data: Lifestyle, Carnivore, Pescatarian, Vegetarian.

**Comment by pedrobaeza** [comment]
You already have partner_gender for the first one

**Comment by max3903** [comment]
@pedrobaeza Good catch. Thanks! I just removed it from this issue.

**Comment by lasley** [comment]
Maybe instead of a Medical tab, just add into the `Personal Information` tab that the gender and birthdate go under:

![image](https://cloud.githubusercontent.com/assets/7397578/20365352/7906f960-abfb-11e6-9610-272d75422711.png)

We just finished completely removing the Medical tab from vertical medical 😆 . It would conflict in v8 and 9 though.

**Comment by max3903** [comment]
@lasley Done. Thanks!

**Comment by lasley** [comment]
Question on the allergies. Given the context, it seems like maybe we want the term `allergen` instead?

Looking at the nutritional goals, it would be interesting if the `weight` was tracked over time instead of simple float. Maybe I'm getting too far ahead though.

**Comment by max3903** [comment]
@lasley My scope does not include the history, but it would be easy for another module to make this field get the last value from the weight history. Same with height if you want to track it for children.

**Comment by NL66278** [comment]
I think the name partner_nutrition_meal will set people on a wrong footing on what it is about. It looks like a reference to some kind of meal. What about partner_nutrition_style, or maybe partner_nutrition_lifestyle?

**Comment by yajo** [comment]
When your product.product is a meal, don't you have any place where to store its ingredients? Those would be the allergens, not the product.product (imagine you have hunderds of different meals with same ingredients...).

Maybe [product_custom_info](https://github.com/OCA/product-attribute/pull/177) would fit there.

**Comment by max3903** [comment]
@NL66278 what about `diet`?

@Yajo A meal and its ingredients will be product.product and the BOM will have the recipe.

**Comment by max3903** [comment]
Anyone to review the last 5 PR? Everything is green.

**Comment by lasley** [comment]
I'll hit up the ones I haven't reviewed & add approvals to the changes today

**Comment by max3903** [comment]
@lasley Thank you very much!

**Comment by AaronHForgeFlow** [comment]
In my opinion all these modules should go to a vertical-medical repo not the partner-contact

**Comment by lasley** [comment]
@aheficent Vertical Medical is already quite large, and my team struggles to maintain it. I hesitate to expand the scope to include Health contexts, which are mutually exclusive from Medical contexts, due to the current struggles there. 

We do glue some of these modules in using [`medical_agpl`](https://github.com/OCA/vertical-medical/pull/174), but really they are just nice to haves and only for a subset of medical specialties.

My personal preference is the creation of a Vertical Health PSC. You may read the history of that proposal [in the mailing list](https://www.odoo-community.org/groups/contributors-15/contributors-48397?mode=date&date_begin=2016-12-01&date_end=2017-01-01), but it was ultimately denied.
