### ISSUE TITLE
RFC - Keep partner data immutable for history purpose

### ISSUE THREAD

**Issue by bealdav** [OCA/partner-contact#404]
As you Odoo res.partner concept don't keep history.

If you update a contact (address), older sales, picking and invoices address are also impacted by the update, even the oldiest.

I think we could find a way to keep history, at least for shipping address and invoice address.

### Approach 1
- when validating a Sale Order (same on picking and invoice) the linked address should be archived. This mean copying the existing address and creating an new one with active=False and not editable. This archived address will be used in the invoice, shipping...
- When validating an invoice or a shipping we do the same but if the address was already archived (from an sale order) we do not archived if again
- If you modify the delivery address after the sale order validation and before the shipping expedition a new archived address is created (We may use a wizard for this changed)
- when a Picking is validated we archived the address if not already archived
- when a Invoice is confirm we archived the address if not already archived
- we can have 3 modules, 1 for invoice, 1 for delivery and 1 for sale
- an archived address is always in readonly
- when creating an archived address we always look if an existing archived address already exist and always used an existing archived address instead of creating a new one

### Approach 2
- When editing an partner contact we always create a new contact with the new value and we archived the previous contact.
- When we edit a contact from a sale order, a picking or a invoice we should also replace many2one to use the new address created

**Comment by legalsylvain** [comment]
Hi @bealdav. I'm not very in favor to create and archive new partners for that purpose. This is a reccurent problem that should be fixed with another approach, more lighter with a computed field, stored, that is invalidated when the order is confirmed.

### Approach 3

on purchase order, create a new field

```

delivery_adress_text = fields.Char(
    'delivery adress', compute=_compute_delivery_adress_text, store=True)

@api.depends('state')
def _compute_delivery_adress_text(self):
    for partner in self:
        if partner.state == 'confirmed':
            partner.delivery_adress_text = xxx
```
After, use this field instead of the partner adress.
That feat with the reality. When an order is confirmed, the delivery place is chosen and shouldn't change, even if the partner adress changes. (we can imagine a refresh button to update the field manually, calling the _compute_delivery_adress_text function)

It could be a simple community module to do.

what do you think ?

**Comment by lasley** [comment]
This is one of my pain points with Odoo, and would be great to solve. I agree with @legalsylvain on not being in favor of creating new partners - it seems to me like we'd see a lot of edge cases.

I think the proposed approach 3 could be viable, but I wonder if we're being a bit narrow sighted here. An example would be the related stock pickings, which still look as if they were delivered to the new address. All of the reports & templates would still be pointing to the partner too, which I think could be an exponential issue as well.

Something I've been toying with for HIPAA compliance is record versioning. I'm still in incredibly theoretical realm with it, but the goal would be to allow a date to be provided as a context when working with versioned records. Something like this:

```
OldPartners = self.env['res.partner'].with_context(
    version_date='2015-01-23 01:23:45'
)
old_partner = OldPartners.browse(1)
```
Which would then construct the records as they existed in the provided time. 

This isn't necessarily too difficult to accomplish, but making it efficient is. Supporting searches in an alternate timeline is a real hypothetical challenge too. Versioned records related to non-versioned records will also be a pain, creating a disparity of timelines within datasets (assuming we don't just version everything - which is not a good idea IMO).

**Comment by pedrobaeza** [comment]
My procedure for this would be (without changes):

1) Have always a delivery child res.partner, although being the same as the parent one. Use that one for deliveries.
2) If the address changes, disable that partner and create another one with the new address.

Point 1 can be automated.

**Comment by bealdav** [comment]
@legalsylvain Yes it seems your approach is the easiest, thanks It's the way most ERP do the job.
But I think it implies to make db grow up with a lot of repeated informations. Most of usual customers don't change address often

And our db are now big after 7 or 8 years of tiny... to big erp ;-)

Personnally I prefer approach 2.

Let other people express themself
ping @guewen @rvalyi @JayVora-SerpentCS @hbrunn @sbidoul @alexis-via

**Comment by legalsylvain** [comment]
Hi @lasley.
Indeed your ```with_context(version_date=xxx)``` could be a very great feature !  (**approach 4**) and could be made in a very generical way ! Like ```track_visibility``` feature, we could imagine a history_enabled = True on fields. If yes, all changes could be archived. (After the with_context could be easy (more or less) to implement). I wonder if such features have not been implemented yet...

But, it doesn't make more easy changes in reporting and templates. (because all calls should be overloaded too).

For the approach 3 and 4, the problem of reporting will be fixed with new reporting that makes more easy inheritance mechanism.

@bealdav : Well, the approach 3 is really the approach choosed by Odoo for all the concepts. you have a name on many models that is a copy of data. Name on stock move to know the name of the product. (even if the name of the product changed after)
Data are duplicated for that purpose : to know a value of an object at the given date.

kind regards.

**Comment by lasley** [comment]
@bealdav I think there will be considerable edge cases with archiving partners in approach 2. For example, grouping by partner would no longer be possible. Additionally, what would be the considerations for disparate record associations, such as patients in Medical?

Approach 3 - I guess it's really a question of whether the size introduced by this method hurts you. IMO disk space is incredibly cheap, so the real question is whether it hurts in terms of performance.

The answer to this is yes (slightly), but I would say that this is likely negligible given the consideration that adding this feature guarantees that data will not shift from underneath records that could be needed for historical consideration.

@legalsylvain - Approach 4 - I was thinking something like this, yeah. I haven't been able to find anything though, and was fairly close to making an RFC. It's probably overkill here though, so just keep an eye out in `server-tools` 😉

**Comment by sebastienbeau** [comment]
@lasley In fact you do not have more issue with group by then in the natif case. Group by should be done on the commercial_partner_id (the parent). As archived address are always liked to the parent the commercial_partner_id will be correct. In case that you want to filter on the contact of the company that have done an order to your team, in this case the group by will not work correctly but I do not think this is a major issue most of the time you want to group on the company that make the order). I you still need this analyses, you can add a field "partner_name" and group by commercial_partner_id and partner_name to have more details.

@legalsylvain adding computed field can be a solution, but if you want to be able to do analyses you should store all data separately (zip, state, country, street...). Magento and Prestashop have taken this option. For me having the data separately store in the table sale order or invoice is a possible solution (It's like the approche 1 but we store this data in the table sale, invoice, picking). But as in Odoo we use everythere the table partner (report, analyses, carrier module...) I think it's less work to store it in the table res.partner

**Comment by NL66278** [comment]
If you want to search sales, invoices, deliveries etc. on city, or country or whatever in address, you will not be able to use text fields containing the full address. So for me this takes out approach .3

The problem with a really good approach, that is with a fully relational database, is that the concepts or partner and partner address have been merged, which in my opinion was a huge design blunder. Of course if a company or person moves, it does not become a new company or person. Unfortunately, for the time being we have to live with this incredibly unfortunate design. 

Approach 2 will make it really difficult to follow the history of a partner. A partner moves and suddenly the amount of sales to this partner - for example - will become zero.

So it would be most logical to always have a separate invoice and delivery address. This should also always be an active=False read-only copy of the main partner/delivery/invoice address. So this is basically approach 1. This can be finetuned by not creating a NEW copy, but reusing the old one, if no address field changed.

I think this would minimize database size, will still allowing all searching and grouping and satisfy the requirement for having reliable historically correct data.

**Comment by mourad-ehm** [comment]
The mix of proposed approaches can give this approach: 
1. create an object that contains address fields (street, city, zip, ....) and a field address_version.
2. The version can be 1, 2, 3, 4 .... (I prefer number to "date" because easy to handle)
3. add a field address_version on sale.order, stck.picking, account.invoice. 
4. at the validation time of sale, picking, invoice, .. we store the last address version (we create a new address version if partner has no version).
In this manner we can make search and statistics by city, country, ... . And reduce db size (the same address version can be used for several objects (sales, invoices, ...).
5. For each modification address partner, we can create an address version (check box "adrees_version" True/False can be used the avoid address version creation for some partners )
**For reports**
1. Use store attachment file (like invoice) to keep the pdf archived,
2. Or, Override read method of res.parther  with with_context(address_version=xxx) and replace adrress fields by those of version address

**Comment by bealdav** [comment]
:+1: for mourad proposal

**Comment by sebastienbeau** [comment]
Just for information In Tryton they have the concept of history_table see here http://hg.tryton.org/trytond/rev/7d205b181b4c
If you modify a partner record they insert the history value in this special table. It can be solution to implement what @lasley was proposing.

Adding a new table for storing the historical value may make hard the reporting / analysis / group by because you have to join data between real and history table. Moreover adding a new table mean to implement all the logic for adding all additional field on the partner into the table history.

Like @NL66278, I think using approch 1 with a smart copy (searching an existing archived address) can be a good solution to solve the duplication of data. Moreover the implementation is really simple. Validating a sale order, picking, or invoice => creating a new archived address if necessary.

**Comment by lasley** [comment]
@sebastienbeau - Thanks for the pointer on how Tryton does history, I think I'm going to run with this as part of OCA/server-tools#787

**Comment by johnrisby** [comment]
I just discovered this problem on Friday after months of work on an Odoo implementation. Absolutely staggered it works like this. I spoke to someone on live chat and she suggested I try EE (I'm currently on CE) but I wasn't in the mood then after a stressful afternoon wondering if I had wasted my time so far.

She said she was going to pass it on to a developer to find out if EE worked this way (I was 99.9% sure it would) and find out why it was doing this. So far (Monday evening) I've heard nothing back.

I tried an EE test today on their online trial and of course it does work the same way. Edit an address and previous orders get changed. How is this remotely possible? Who thought this was acceptable?

I've been told 'Ah but Odoo isn't an ecommerce system, it's an ERP with ecommerce features' (not by Odoo, by a developer) but that's nonsense. It may be an ERP but they sell it as having full ecommerce features. Not toy ones.

It's impossible to work with a system that edits previous orders like this. Especially when with the ecommerce site the customer can edit their own address (and so they should).

Again, I've been told a simple 'customisation' like Approach 3 would solve it (although fixing a basic design flaw is not customisation in my book), but reading further in this thread it seems it's not that simple as other parts of Odoo link to the partner model too. So it's not that simple.

It really makes me wonder if Odoo ecommerce is remotely ready for the real world and if they take it seriously. 

Does anyone have a fix for this or any other ideas? At the moment I feel like jacking it in, giving up on a lot of lost time, and moving to another system. I don't want to. But this is fundamentally broken.

**Comment by lasley** [comment]
@johnrisby - All known progress on this task can be read in this issue. Our community welcomes any contribution you would like to provide on this, but please don't just complain in an open source forum. Your complaints should be directed at authors of the software, Odoo SA, not the Odoo Community Association.

**Comment by johnrisby** [comment]
@lasley I'm sorry if you saw it as a complaint against OCA but it isn't. I have taken it up with Odoo but without reply so far. I just hoped someone may have some further information and given that the Odoo 'forum' isn't a discussion forum, and this issue is about the problem I just discovered, I thought I'd ask. If there is somewhere better to discuss it, please let me know. For what it's worth, I fixed a similar problem this year with Sylius (except it was about products in orders not being immutable, rather than addresses). I raised the problem, and wrote the first version of the PR which was tidied up by another developer and added to the core. But I'm not in the position to do it again with another system. I just need to get a new shop up and running.

**Comment by mourad-ehm** [comment]
ping @hparfr

**Comment by sebastienbeau** [comment]
Hi all, after thinking a lot about it. We are going to implement the approche 1.
- It simple to implement
- it will only duplicate address if needed
- it work when we have only one partner (as the archived address will be a contact of the partner)
We will do it during the OCA code sprint (you can follow this track in shopinvader dashboard : https://trello.com/b/oWwLLHkZ/shopinvader)

**Comment by pedrobaeza** [comment]
It would be convenient to avoid to duplicate archived addresses when multiple sales orders.

**Comment by sebastienbeau** [comment]
Yes, it's planned ! When we create an archive address, we check first if an archive address with same value already exist, if yes we reuse it if not we create a new one.

**Comment by pedrobaeza** [comment]
You can create a new field called address_hash or similar that it's computed when any of the address fields changes, and then you only need to search by that field.

**Comment by sebastienbeau** [comment]
it seem to be a good idea

**Comment by bealdav** [comment]
really good idea, yes

**Comment by infoitservit** [comment]
Wow, I'm in the same situation of @johnrisby , amazing Odoo didn't take these procedures as granted!
I was looking for the @sebastienbeau 's trello dashboard but i can't find nothing. Someone should point me to te right direction? I'm implementing Odoo11 since two months, I really hope to find a solution to this strange situation.

**Comment by bguillot** [comment]
I propose a solution for this here : https://github.com/OCA/partner-contact/pull/669
