### ISSUE TITLE
Partner_names_order SET NOT NULL' ERROR

### ISSUE THREAD

**Issue by source-promo** [OCA/partner-contact#734]
Dear all,
I noticed following error when upgrading Odoo modules:

```
ERROR source-promo-odoo-master-370999 odoo.sql_db: bad query: b'ALTER TABLE "res_config_settings" ALTER COLUMN "partner_names_order" SET NOT NULL'
ERROR: column "partner_names_order" contains null values

2019-05-04 17:43:47,586 1279 WARNING source-promo-odoo-master-370999 odoo.schema: Table 'res_config_settings': unable to set NOT NULL on column 'partner_names_order'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "res_config_settings" ALTER COLUMN "partner_names_order" SET NOT NULL
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "partner_names_order" contains null values
```

Hope you can help me what to do and where this is coming from!
Thanks in advance!

**Comment by yvaucher** [comment]
@source-promo this happens when you install a module that adds a constraint but your data don't respect that constraint.

In your case the data error was coming from the table res_config_settings which is a TransientModel. You might have had at some point some old instances of wizard in that table and zero value in the column `partner_names_order`

This would resolve itself after wizard rows in database are garbage collected or if you empty the table res_config_settings manually.

The issue here is that no default value is set for that field. Thus old records are not filled.
To avoid this module without manual operation it would require a fix that either empty the table res_config_settings or fill the column with the default value `first_last`
