### ISSUE TITLE
[10.0] partner_sale_risk: sale order state in done

### ISSUE THREAD

**Issue by rafamarpe** [OCA/partner-contact#759]
Hi,

When the sales order settings are set so that they cannot be modified, the created orders are not taken into account for the financial risk in the sales orders.
Is it for any reason? Should these orders not be taken into account since they are also ordered?

Thanks

**Comment by pedrobaeza** [comment]
@carlosdauden can you answer this?

**Comment by carlosdauden** [comment]
This is a mechanism to discard the compute of risk in sales orders that will never be delivered.
When the products of an order are billed quantities delivered, less than ordered qty are delivered and nothing will be delivered again, we have to have a way to mark the order so that the amount pending in the risk is not taken into account.
Creating a new field in sale order is a worsening of the UX.
Maybe you can make a PR to propose a change by creating a hook `get_sale_risk_domain()` to easily customize or add an option to company level to determine if done state orders are included:
https://github.com/OCA/partner-contact/blob/10.0/partner_sale_risk/models/res_partner.py#L28

**Comment by rafamarpe** [comment]
Hi Carlos.
I understand what you want to say but since odoo is the one who directly blocks the order, I think that the orders should be taken into account in a locked state although it is also true that there must be something that indicates that the order is invoiced, I do not know if In that case, the "invoice state" field can help.

**Comment by pedrobaeza** [comment]
Odoo doesn't block this. It's your configuration that does that... You can configure it for not auto-blocking.

**Comment by rafamarpe** [comment]
Pedro is correct, but if as a user you do not want an order to be edited once confirmed what odoo does is to fit the status directly to done

**Comment by pedrobaeza** [comment]
Yeah, but that case is not covered now in the modules. You can do a pull request doing one of things stated by my colleague or checking if `invoice_status` can serve.
